# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20161017_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secrets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_author', to='login.User')),
                ('likes', models.ManyToManyField(related_name='secrets', to='login.User')),
            ],
        ),
    ]
